apiVersion: v1
kind: Service
metadata:
  name: devcalc-api-service
  labels:
    app: devcalc-api
spec:
  type: NodePort
  selector:
    app: devcalc-api
  ports:
    - name: http
      port: 7000
      targetPort: 7000
      nodePort: 30080
